#!/bin/bash
BOLD=`tput bold`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
GREENBOLD=$BOLD$GREEN
REDBOLD=$BOLD$RED
RESET=`tput init`


git diff --staged | grep -v ^- | grep "console.log" 2> /dev/null 1> /dev/null
if [ $? = 0 ]
then
      echo "${REDBOLD}/!\\Console.log detected /!\\"
      echo "${REDBOLD}aborting..."
      exit 1
else
      echo "${GREENBOLD} No console.log"
fi

git diff --staged | grep -v ^- | grep "<<<<<<< HEAD" 2> /dev/null 1> /dev/null
if [ $? = 0 ]
then
      echo "${REDBOLD}/!\\ UNRESOLVED MERGE DETECTED /!\\"
      echo "${REDBOLD}aborting..."
      exit 1
else
      echo "${GREENBOLD} No unresolved merge"
fi


echo $RESET
